# Generated by Django 6.0.7 on 2026-07-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_gstin', models.CharField(max_length=50)),
                ('seller_pin', models.CharField(max_length=20)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_gstin', models.CharField(max_length=50)),
                ('buyer_billing_address', models.TextField()),
                ('buyer_pin', models.CharField(max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('irn', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('e_invoice_status', models.CharField(default='NotGenerated', max_length=20)),
                ('e_invoice_generated_at', models.DateTimeField(blank=True, null=True)),
                ('e_way_bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('transporter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('e_way_bill_status', models.CharField(default='NotGenerated', max_length=20)),
                ('e_way_bill_generated_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_sent_status', models.CharField(default='NotSent', max_length=20)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('bill_type', models.CharField(default='Invoice', max_length=20)),
                ('template_type', models.CharField(default='Standard', max_length=50)),
                ('invoice_theme_color', models.CharField(default='#2563eb', max_length=20)),
                ('store_snapshot', models.JSONField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tally_guid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_synced_to_tally', models.BooleanField(default=False)),
                ('tally_sync_date', models.DateTimeField(blank=True, null=True)),
                ('compliance_audit_status', models.CharField(default='Pending', max_length=20)),
                ('compliance_flags', models.JSONField(default=list)),
                ('compliance_confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_rate', models.IntegerField()),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_tax_inclusive', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
    ]
