# Generated by Django 6.0.7 on 2026-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='IntellectBill AI Operations', max_length=255)),
                ('address', models.TextField(default='101, Business Enclave, Cyber City, Sector 45, Gurgaon, Haryana')),
                ('phone_number', models.CharField(default='+919876543210', max_length=20)),
                ('email', models.EmailField(default='billing@intellectbill.ai', max_length=254)),
                ('gstin', models.CharField(default='27AAAAA1111A1Z1', max_length=15)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('default_invoice_template', models.CharField(choices=[('Standard', 'Standard'), ('Modern', 'Modern'), ('Thermal', 'Thermal'), ('TaxInvoice', 'TaxInvoice'), ('Minimalist', 'Minimalist'), ('Commercial', 'Commercial'), ('Proforma', 'Proforma')], default='Standard', max_length=50)),
                ('invoice_theme_color', models.CharField(default='#2563eb', max_length=20)),
                ('business_type', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Manufacturing', 'Manufacturing')], default='Retail', max_length=50)),
                ('printer_type', models.CharField(choices=[('Regular', 'Regular'), ('Thermal', 'Thermal')], default='Regular', max_length=50)),
                ('regular_layout_theme', models.CharField(default='Standard', max_length=50)),
                ('regular_theme_color', models.CharField(default='#2563eb', max_length=20)),
                ('print_repeat_header', models.BooleanField(default=False)),
                ('print_company_name', models.BooleanField(default=True)),
                ('custom_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('print_company_logo', models.BooleanField(default=True)),
                ('custom_logo_url', models.URLField(blank=True, null=True)),
                ('print_address', models.BooleanField(default=True)),
                ('custom_address', models.TextField(blank=True, null=True)),
                ('print_email', models.BooleanField(default=True)),
                ('custom_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('print_phone', models.BooleanField(default=True)),
                ('custom_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('print_gstin', models.BooleanField(default=True)),
                ('custom_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('auto_send_whatsapp', models.BooleanField(default=False)),
                ('paper_size', models.CharField(default='A4', max_length=20)),
                ('orientation', models.CharField(default='Portrait', max_length=20)),
                ('company_name_text_size', models.CharField(default='Large', max_length=20)),
                ('invoice_text_size', models.CharField(default='Large', max_length=20)),
                ('print_total_qty', models.BooleanField(default=True)),
                ('amount_with_decimal', models.BooleanField(default=True)),
                ('print_received_amount', models.BooleanField(default=True)),
                ('print_balance_amount', models.BooleanField(default=False)),
                ('print_current_balance', models.BooleanField(default=False)),
                ('print_tax_details', models.BooleanField(default=True)),
                ('print_you_saved', models.BooleanField(default=False)),
                ('print_amount_with_grouping', models.BooleanField(default=True)),
                ('amount_in_words_format', models.CharField(default='Indian', max_length=50)),
                ('company_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('po_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('print_bank_details', models.BooleanField(default=False)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('print_description', models.BooleanField(default=True)),
                ('thermal_printing_type', models.CharField(default='Text Printing', max_length=50)),
                ('thermal_use_text_styling_bold', models.BooleanField(default=True)),
                ('thermal_auto_cut', models.BooleanField(default=True)),
                ('thermal_open_cash_drawer', models.BooleanField(default=True)),
                ('thermal_extra_lines', models.IntegerField(default=0)),
                ('thermal_copies', models.IntegerField(default=1)),
                ('thermal_print_company_name', models.BooleanField(default=True)),
                ('thermal_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
