# Generated by Django 6.0.7 on 2026-07-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=18)),
                ('is_tax_inclusive', models.BooleanField(default=True)),
                ('tally_guid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_order_quantity', models.IntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_of_materials_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='products.product')),
            ],
        ),
    ]
